/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EmfaticUiModule extends AbstractEmfaticUiModule {

	public EmfaticUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
