/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext.scoping;

import java.util.Objects;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.emfatic.xtext.emfatic.EmfaticPackage;
import org.eclipse.xtext.scoping.IScope;
import org.eclipse.xtext.scoping.impl.FilteringScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class EmfaticScopeProvider extends AbstractEmfaticScopeProvider {

	@Override
	public IScope getScope(EObject context, EReference reference) {
		if (reference == EmfaticPackage.Literals.DATA_TYPE_WITH_MULTI__TYPE) {
			return new FilteringScope(
					super.getScope(context, reference),
						(e) -> 
							Objects.equals(e.getEClass(), EmfaticPackage.Literals.DATA_TYPE_DECL));
		}
		return super.getScope(context, reference);
	}
}
