/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.emf.emfatic.xtext.EmfaticRuntimeModule;
import org.eclipse.emf.emfatic.xtext.EmfaticStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EmfaticIdeSetup extends EmfaticStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EmfaticRuntimeModule(), new EmfaticIdeModule()));
	}
	
}
