/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class EmfaticIdeModule extends AbstractEmfaticIdeModule {
}
