/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext;

import org.eclipse.emf.emfatic.xtext.scoping.EmfaticGSP;
import org.eclipse.xtext.scoping.IGlobalScopeProvider;
import org.eclipse.xtext.scoping.impl.DefaultGlobalScopeProvider;

/**
 * Use this class to register components to be used at runtime / without the 
 * Equinox extension registry.
 */
public class EmfaticRuntimeModule extends AbstractEmfaticRuntimeModule {

	
	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
		return EmfaticGSP.class;
	}
	
}
