/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext;


// TODO: Auto-generated Javadoc
/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmfaticStandaloneSetup extends EmfaticStandaloneSetupGenerated {

	/**
	 * Do setup.
	 */
	public static void doSetup() {
		new EmfaticStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
