/*
 * generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmfaticStandaloneSetup extends EmfaticStandaloneSetupGenerated {

	public static void doSetup() {
		new EmfaticStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
