/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.emfatic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EmfaticStandaloneSetup extends EmfaticStandaloneSetupGenerated {

	public static void doSetup() {
		new EmfaticStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
