/*
* generated by Xtext 2.28.0
 */
package org.eclipse.emf.emfatic.xtext.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.io.InputStream;
import java.net.URISyntaxException;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.emfatic.xtext.emfatic.Annotation;
import org.eclipse.emf.emfatic.xtext.emfatic.BoundExceptWildcard;
import org.eclipse.emf.emfatic.xtext.emfatic.ClassDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.ClassMemberDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.CommaListBoundExceptWild;
import org.eclipse.emf.emfatic.xtext.emfatic.CompUnit;
import org.eclipse.emf.emfatic.xtext.emfatic.DataTypeDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.EnumDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.Import;
import org.eclipse.emf.emfatic.xtext.emfatic.KeyEqualsValue;
import org.eclipse.emf.emfatic.xtext.emfatic.KeyEqualsValueList;
import org.eclipse.emf.emfatic.xtext.emfatic.MapEntryDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.Operation;
import org.eclipse.emf.emfatic.xtext.emfatic.PackageDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.Param;
import org.eclipse.emf.emfatic.xtext.emfatic.StringOrQualifiedID;
import org.eclipse.emf.emfatic.xtext.emfatic.SubPackageDecl;
import org.eclipse.emf.emfatic.xtext.emfatic.TopLevelDecl;
import org.eclipse.xtext.resource.XtextResourceSet;
import com.google.inject.Provider;

@ExtendWith(InjectionExtension.class)
@InjectWith(EmfaticInjectorProvider.class)
class EmfaticEcoreTest {
	
	@Inject
	private Provider<XtextResourceSet> resourceSetProvider;
	
	@Inject
	private ParseHelper<CompUnit> parseHelper;
	
	
	@Test
	void mainPackage() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		PackageDecl pckg = compUnit.getPackage();
		Assertions.assertEquals(1, pckg.getAnnotations().size());
		Annotation namespace = pckg.getAnnotations().get(0);
		StringOrQualifiedID source = namespace.getSource();
		Assertions.assertNull(source.getLiteral());
		Assertions.assertEquals("namespace", source.getId());
		KeyEqualsValueList values = namespace.getValues();
		Assertions.assertEquals(2, values.getKv().size());
		KeyEqualsValue keyVal = values.getKv().get(0);
		Assertions.assertEquals("uri", keyVal.getKey());
		Assertions.assertEquals("http://www.eclipse.org/emf/2002/Ecore", keyVal.getValue());
		keyVal = values.getKv().get(1);
		Assertions.assertEquals("prefix", keyVal.getKey());
		Assertions.assertEquals("ecore", keyVal.getValue());
	}
	
	@Test
	void importStmts() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<Import> imports = compUnit.getImportStmts();
		Assertions.assertEquals(0, imports.size());
	}
	
	@Test
	void topLevelDecls() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		Assertions.assertEquals(52, topLevelDecls.size());
	}
	
	@Test
	void subPacakges() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		List<TopLevelDecl> subPacakges = topLevelDecls.stream()
			.filter(tld -> tld.getDecl() instanceof SubPackageDecl)
			.collect(Collectors.toList());
		Assertions.assertEquals(0, subPacakges.size());
	}
	
	@Test
	void classes() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		List<TopLevelDecl> classes = topLevelDecls.stream()
				.filter(tld -> tld.getDecl() instanceof ClassDecl)
				.collect(Collectors.toList());
		Assertions.assertEquals(20, classes.size());
	}
	
	@Test
	void datatypes() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		List<TopLevelDecl> datatypes = topLevelDecls.stream()
				.filter(tld -> tld.getDecl() instanceof DataTypeDecl)
				.collect(Collectors.toList());
			Assertions.assertEquals(32, datatypes.size());
	}
	
	@Test
	void enums() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		List<TopLevelDecl> enums = topLevelDecls.stream()
			.filter(tld -> tld.getDecl() instanceof EnumDecl)
			.collect(Collectors.toList());
		Assertions.assertEquals(0, enums.size());
	}
	
	@Test
	void mapentries() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		EList<TopLevelDecl> topLevelDecls = compUnit.getTopLevelDecls();
		List<TopLevelDecl> mapentries = topLevelDecls.stream()
			.filter(tld -> tld.getDecl() instanceof MapEntryDecl)
			.collect(Collectors.toList());
		Assertions.assertEquals(0, mapentries.size());
	}
	
	@Test
	void eAttributeClass() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		TopLevelDecl declaration = compUnit.getTopLevelDecls().stream()
				.filter(tld -> tld.getDecl() instanceof ClassDecl
						&& Objects.equals("EAttribute", ((ClassDecl)tld.getDecl()).getName()))
				.findFirst()
				.orElseThrow();
		// Annotation
		Assertions.assertEquals(1, declaration.getAnnotations().size());
		Annotation annot = declaration.getAnnotations().get(0);
		StringOrQualifiedID source = annot.getSource();
		Assertions.assertNull(source.getLiteral());
		Assertions.assertEquals("Ecore", source.getId());
		KeyEqualsValueList values = annot.getValues();
		Assertions.assertEquals(1, values.getKv().size());
		KeyEqualsValue keyVal = values.getKv().get(0);
		Assertions.assertEquals("constraints", keyVal.getKey());
		Assertions.assertEquals("ConsistentTransient", keyVal.getValue());
		// Class
		ClassDecl cls = (ClassDecl) declaration.getDecl();
		Assertions.assertFalse(cls.isAbstract());
		Assertions.assertEquals("class", cls.getKind());
		Assertions.assertNull(cls.getTypeParamsInfo());
		EList<BoundExceptWildcard> superTypes = cls.getSuperTypes().getTb();
		Assertions.assertEquals(1, superTypes.size());
		Assertions.assertEquals("EStructuralFeature", superTypes.get(0).getName());
		Assertions.assertNull(superTypes.get(0).getTypeArgs());
		Assertions.assertNull(cls.getInstClassName());
		Assertions.assertEquals(2, cls.getMembers().size());
	}
	
	
	@Test
	void classMemberDecl() throws URISyntaxException {
		InputStream complete = getClass().getResourceAsStream("/ecore.emf");
		URI uri = URI.createURI(getClass().getResource("/ecore.emf").toURI().toString());
		CompUnit compUnit = parseHelper.parse(complete, uri, null, resourceSetProvider.get());
		ClassDecl eClass = compUnit.getTopLevelDecls().stream()
				.filter(tld -> tld.getDecl() instanceof ClassDecl
						&& Objects.equals("EClass", ((ClassDecl)tld.getDecl()).getName()))
				.map(tld -> (ClassDecl) tld.getDecl())
				.findFirst()
				.orElseThrow();
		// Operations
		List<Operation> ops = eClass.getMembers().stream()
				.filter(m -> m.getMember() instanceof Operation)
				.map(m -> (Operation) m.getMember())
				.collect(Collectors.toList());
		Assertions.assertEquals(5, ops.size());
		Operation getFeatureCount = ops.stream()
				.filter(op -> Objects.equals("getFeatureCount", op.getName()))
				.findFirst()
				.orElseThrow();
		Assertions.assertEquals("EInt", getFeatureCount.getResType().getType().getType().getName());
		Assertions.assertNull(getFeatureCount.getParams());
		Operation getEStructuralFeature = ops.stream()
				.filter(op -> Objects.equals("getEStructuralFeature", op.getName()))
				.findFirst()
				.orElseThrow();
		Assertions.assertEquals("EStructuralFeature", getEStructuralFeature.getResType().getType().getType().getName());
		Assertions.assertEquals(1, getEStructuralFeature.getParams().getP().size());
		Param featureID = getEStructuralFeature.getParams().getP().get(0);
		Assertions.assertEquals("featureID", featureID.getName());
		Assertions.assertEquals(0, featureID.getLeadingAnnotations().size());
		Assertions.assertEquals(0, featureID.getTrailingAnnotations().size());
		Assertions.assertEquals(0, featureID.getModifiers().size());
		Assertions.assertEquals("EInt", featureID.getType().getType().getName());
		// Attributes
		
		
	}
	
}