/*
 * generated by Xtext 2.25.0
 */
package org.eclipse.emfatic.ide;

import org.eclipse.emfatic.ide.contentassist.EmfaticContentProposalProvider;
import org.eclipse.xtext.ide.editor.contentassist.IdeContentProposalProvider;
import org.eclipse.xtext.service.SingletonBinding;

/**
 * Use this class to register ide components.
 */
public class EmfaticIdeModule extends AbstractEmfaticIdeModule {

	@SingletonBinding(eager = true)
	public Class<? extends IdeContentProposalProvider> bindIdeContentProposalProvider() {
		return EmfaticContentProposalProvider.class;
	}
}
